### ISSUE TITLE
Cellstate 3 should be white.

### ISSUE THREAD

**Issue by hanss314** [HTStem/Golad.io#11]
It's what the gamestrings use and considering there's plans for other rules, it should be added.

**Comment by Bottersnike** [comment]
Cellstate 3?

**Comment by hanss314** [comment]
In this version, if the state of a cell is 3, it's a half born red, for game string compatibility, could you make state 3 white and states 4 and 5 the half born states.

**Comment by Bottersnike** [comment]
Ahh. Okay.
