### ISSUE TITLE
Fix the move numbers

### ISSUE THREAD

**Issue by hanss314** [HTStem/Golad.io#8]
I added a section to my [documentation](https://docs.google.com/document/d/1r_4uu2KiomTVjG57WF1ckY2Uw5Z7mh2uzQCX7Vsu_tI/edit)
Essentially, the it's (move) out of (latest move). Not (red moves)/(blue moves). The move on the left changes during undos the one on the right only increases (kinda). Please fix.

**Comment by Bottersnike** [comment]
Cool. Thanks. I'll work on this soon. I'm working on STEM-Bote RN.

**Comment by hanss314** [comment]
Not anymore botter
